package Etudiant;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fares
 */
public class F_S_L extends javax.swing.JFrame {
    static LinkedList<String> liste = new LinkedList<>();
    /**
     * Creates new form JFrame3
     */
    public F_S_L() {
        
        initComponents();
        jPanel1.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Text2 = new javax.swing.JLabel();
        Input = new javax.swing.JTextField();
        bnt4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_R = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        d_pret = new javax.swing.JTextField();
        d_restitution = new javax.swing.JTextField();
        c_pret = new javax.swing.JTextField();
        n_ordre = new javax.swing.JTextField();
        id_pret = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        B6 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(540, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Back.png"))); // NOI18N
        B5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B5MouseClicked(evt);
            }
        });
        getContentPane().add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 30, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        Text2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        Text2.setForeground(new java.awt.Color(255, 255, 255));
        Text2.setText("Saisir votre recherche :");

        bnt4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Search.png"))); // NOI18N
        bnt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Text2)
                .addGap(115, 115, 115))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Input, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bnt4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(Text2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bnt4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Input))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 340, 60));

        tb_R.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Identifient", "Editeur", "Titre", "Pays", "Nb_exemplaire", "ISBN", "Date_edition", "CDD", "Theme", "Langage", "Nom auteur", "Prenom auteur"
            }
        ));
        tb_R.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_RMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_R);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 590, 350));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Date de prêt:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date de restitution:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Numéro d'ordre d'emprenteur:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Catégorie de prêt:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Identifiant de la catégorie:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        d_pret.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(d_pret, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 80, -1));

        d_restitution.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(d_restitution, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 80, -1));

        c_pret.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(c_pret, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 80, -1));

        n_ordre.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(n_ordre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 80, -1));

        id_pret.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(id_pret, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 80, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("(JJ/MM/AAA)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 70, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("(JJ/MM/AAA)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 80, -1, 20));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Home.png"))); // NOI18N
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, -1));

        B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Add.png"))); // NOI18N
        B6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B6MouseClicked(evt);
            }
        });
        getContentPane().add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Background.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_RMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_RMouseClicked
        DefaultTableModel model = (DefaultTableModel) tb_R.getModel();
        int selectedRowIndex = tb_R.getSelectedRow();
        
        c_pret.setText(liste.getFirst());
        id_pret.setText(model.getValueAt(selectedRowIndex, 0).toString());
    }//GEN-LAST:event_tb_RMouseClicked

    private void B5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5MouseClicked
        new S_livre_1().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_B5MouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        new Library().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeMouseClicked

    private void bnt4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt4MouseClicked
        Connection con = null;
        Statement st = null;
        PreparedStatement pst = null;
        ResultSet rs = null;

        String query = "SELECT * FROM "+liste.getFirst()+" WHERE "+liste.getLast()+" =?";
            try{
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bibliotheque","root","");
                pst = con.prepareStatement(query);
                pst.setString(1, Input.getText());
                rs = pst.executeQuery();
                tb_R.setModel(DbUtils.resultSetToTableModel(rs));
                if(tb_R.getRowCount() == 0)
                JOptionPane.showMessageDialog(null,"Le mot entré n'a pas été trouvé");
            }catch(SQLException ex){
                System.out.println("Error: "+ex);

            }
    }//GEN-LAST:event_bnt4MouseClicked

    private void B6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6MouseClicked
        if(    d_pret.getText().equals("") 
            || d_restitution.getText().equals("") 
            || c_pret.getText().equals("")
            || id_pret.getText().equals("")
            || n_ordre.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "Un ou plusieurs champs sont vides");
        }else{
            String d1 = d_pret.getText();
            String d2 = d_restitution.getText();        
            char[] charArray1 = d1.toCharArray();
            char[] charArray2 = d2.toCharArray();
            
            if(charArray1[2] == '/' && charArray1[5] == '/'){
                if(charArray2[2] == '/' && charArray2[5] == '/'){
                    try {
                        int idPret = Integer.parseInt(id_pret.getText());
                        int nOrdre = Integer.parseInt(n_ordre.getText());
                
                        DB_Managing.InsertPret(d_pret.getText(), d_restitution.getText(), c_pret.getText(), idPret, nOrdre);
                    }catch(SQLException ex){
                     System.out.println("Error: "+ex);
                    }                    
                }else{
                    JOptionPane.showMessageDialog(null, "Vérifier le format de la date de restitution insérée");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Vérifiez le format de date de pret insérée");
            }
        }
    }//GEN-LAST:event_B6MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel B5;
    private javax.swing.JLabel B6;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Home;
    private javax.swing.JTextField Input;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel bnt4;
    private javax.swing.JTextField c_pret;
    private javax.swing.JTextField d_pret;
    private javax.swing.JTextField d_restitution;
    private javax.swing.JTextField id_pret;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField n_ordre;
    private static javax.swing.JTable tb_R;
    // End of variables declaration//GEN-END:variables
    
    static void Call(String Id){
                
        liste.add(Id);
        System.out.println("Id = "+Id);
    }
}
