
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fares
 */
public class Books extends javax.swing.JFrame {

    /**
     * Creates new form N_Subscribers
     */
    public Books() {
        initComponents();
        Update_table();
        setDefaultCloseOperation(Books.DISPOSE_ON_CLOSE);
        setIcon();
    }

    private void Update_table(){
    
    Connection con = null;
    Statement st = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    String query = "SELECT * FROM livres";
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bibliotheque","root","");
            pst = con.prepareStatement(query);
            rs = pst.executeQuery();
            tb_Books.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(SQLException ex){
            System.out.println("Error: "+ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Text1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Insert_Books = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        identifient = new javax.swing.JTextField();
        editeur = new javax.swing.JTextField();
        titre = new javax.swing.JTextField();
        pays = new javax.swing.JTextField();
        n_exmp = new javax.swing.JTextField();
        isbn = new javax.swing.JTextField();
        n_auteur = new javax.swing.JTextField();
        p_auteur = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Update_Books = new javax.swing.JLabel();
        Delete_Books = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Books = new javax.swing.JTable();
        langage = new javax.swing.JComboBox<>();
        theme = new javax.swing.JComboBox<>();
        cdd = new javax.swing.JComboBox<>();
        Reset = new javax.swing.JLabel();
        d_edition = new com.toedter.calendar.JDateChooser();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Gestion de la bibliothèque");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Text1.setForeground(new java.awt.Color(255, 255, 255));
        Text1.setText("Livers");
        getContentPane().add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Editeur:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Titre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pays:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Numéro d'exemplaire:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ISBN:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Daté d'édition:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CDD:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Théme:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Langage:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nom auteur:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        Insert_Books.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Add.png"))); // NOI18N
        Insert_Books.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Insert_Books.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Insert_BooksMouseClicked(evt);
            }
        });
        getContentPane().add(Insert_Books, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Identifient:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        identifient.setBackground(new java.awt.Color(204, 204, 204));
        identifient.setEnabled(false);
        getContentPane().add(identifient, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 140, -1));

        editeur.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(editeur, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 140, -1));

        titre.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 140, -1));

        pays.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(pays, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 140, -1));

        n_exmp.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(n_exmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 140, -1));

        isbn.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 140, -1));

        n_auteur.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(n_auteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 140, -1));

        p_auteur.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(p_auteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 140, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Prenom auteur:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        Update_Books.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Update.png"))); // NOI18N
        Update_Books.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Update_BooksMouseClicked(evt);
            }
        });
        getContentPane().add(Update_Books, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        Delete_Books.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Delete.png"))); // NOI18N
        Delete_Books.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Delete_BooksMouseClicked(evt);
            }
        });
        getContentPane().add(Delete_Books, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, -1));

        tb_Books.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Identifient", "Editeur", "Titre", "Pays", "Nb_exemplaire", "ISBN", "Date_edition", "CDD", "Theme", "Langage", "Nom auteur", "Prenom auteur"
            }
        ));
        tb_Books.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_BooksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Books);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 670, 410));

        langage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arabe", "Français", "Anglais ", "Espagnol", "Allemand", "Italien" }));
        getContentPane().add(langage, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 140, -1));

        theme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Analytiques", "Algébrique", "Informatique", "Chimie", "Technologie", "Science" }));
        getContentPane().add(theme, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 140, -1));

        cdd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "000", "100", "200", "300", "400", "500", "600", "700", "800", "900" }));
        getContentPane().add(cdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 140, -1));

        Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Delete_1.png"))); // NOI18N
        Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetMouseClicked(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 30, 20, -1));

        d_edition.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(d_edition, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 140, -1));

        Background.setBackground(new java.awt.Color(204, 204, 204));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Background.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Insert_BooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Insert_BooksMouseClicked
    
    if( 
           editeur.getText().equals("") 
        || titre.getText().equals("") 
        || pays.getText().equals("")
        || n_exmp.getText().equals("")
        || isbn.getText().equals("")
        || d_edition.getDate() == null
        || n_auteur.getText().equals("")
        || p_auteur.getText().equals("")){
            
        JOptionPane.showMessageDialog(null, "Un ou plusieurs champs sont vides");
        }else{
        int nb_exemplaire = Integer.parseInt(n_exmp.getText());
        String Langage = (String) langage.getSelectedItem();
        String Theme = (String) theme.getSelectedItem();
        String Cdd = (String) cdd.getSelectedItem();
            try {
                Date date = d_edition.getDate();    
                java.sql.Date sgldate = new java.sql.Date(date.getTime());
                
                DB_Managing.InsertBooks(editeur.getText(), titre.getText(), pays.getText(), nb_exemplaire, isbn.getText(), sgldate, Cdd, Theme, Langage, n_auteur.getText(), p_auteur.getText());
                Update_table();
                } catch (SQLException ex) {
                    Logger.getLogger(Subscribers.class.getName()).log(Level.SEVERE, null, ex);
                  }
        } 
        
    }//GEN-LAST:event_Insert_BooksMouseClicked

    private void Update_BooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_BooksMouseClicked
    
        if(
               identifient.getText().equals("") 
            || editeur.getText().equals("") 
            || titre.getText().equals("") 
            || pays.getText().equals("")
            || n_exmp.getText().equals("")
            || isbn.getText().equals("")
            || d_edition.getDate().equals("")
            || langage.getSelectedItem().equals("")
            || n_auteur.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "Un ou plusieurs champs sont vides");
        }else{
        int nb_exemplaire = Integer.parseInt(n_exmp.getText());
        int Identifient = Integer.parseInt(identifient.getText());
        String Langage = (String) langage.getSelectedItem();
        String Theme = (String) theme.getSelectedItem();
        String Cdd = (String) cdd.getSelectedItem();
            try {
                Date date = d_edition.getDate();    
                java.sql.Date sgldate = new java.sql.Date(date.getTime());
                
                DB_Managing.UpdateBooks(Identifient, editeur.getText(), titre.getText(), pays.getText(), nb_exemplaire, isbn.getText(), sgldate, Cdd, Theme, Langage, n_auteur.getText(), p_auteur.getText());
                Update_table();
                } catch (SQLException ex) {
                    Logger.getLogger(Subscribers.class.getName()).log(Level.SEVERE, null, ex);
                  }
        }
    }//GEN-LAST:event_Update_BooksMouseClicked

    private void Delete_BooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_BooksMouseClicked
        
        if(identifient.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Le champ numéro d'ordre est vides");
        }else{
            int Identifient = Integer.parseInt(identifient.getText());
            DB_Managing.DeleteBooks(Identifient); 
            Update_table();
        }
    }//GEN-LAST:event_Delete_BooksMouseClicked

    private void tb_BooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_BooksMouseClicked
        
        try {
            DefaultTableModel model = (DefaultTableModel) tb_Books.getModel();
            int selectedRowIndex = tb_Books.getSelectedRow();
            
            identifient.setText(model.getValueAt(selectedRowIndex, 0).toString());
            editeur.setText(model.getValueAt(selectedRowIndex, 1).toString());
            titre.setText(model.getValueAt(selectedRowIndex, 2).toString());
            pays.setText(model.getValueAt(selectedRowIndex, 3).toString());
            n_exmp.setText(model.getValueAt(selectedRowIndex, 4).toString());
            isbn.setText(model.getValueAt(selectedRowIndex, 5).toString());
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(selectedRowIndex, 6).toString());
            d_edition.setDate(date);
            cdd.setSelectedItem(model.getValueAt(selectedRowIndex, 7).toString());
            theme.setSelectedItem(model.getValueAt(selectedRowIndex, 8).toString());
            langage.setSelectedItem(model.getValueAt(selectedRowIndex, 9).toString());
            n_auteur.setText(model.getValueAt(selectedRowIndex, 10).toString());
            p_auteur.setText(model.getValueAt(selectedRowIndex, 11).toString());
        } catch (ParseException ex) {
            Logger.getLogger(Books.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tb_BooksMouseClicked

    private void ResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseClicked
        identifient.setText(null);
        editeur.setText(null);
        titre.setText(null);
        pays.setText(null);
        n_exmp.setText(null);
        isbn.setText(null);
        d_edition.setDate(null);
        n_auteur.setText(null);
        p_auteur.setText(null);
        
    }//GEN-LAST:event_ResetMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Delete_Books;
    private javax.swing.JLabel Insert_Books;
    private javax.swing.JLabel Reset;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Update_Books;
    private javax.swing.JComboBox<String> cdd;
    private com.toedter.calendar.JDateChooser d_edition;
    private javax.swing.JTextField editeur;
    private javax.swing.JTextField identifient;
    private javax.swing.JTextField isbn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> langage;
    private javax.swing.JTextField n_auteur;
    private javax.swing.JTextField n_exmp;
    private javax.swing.JTextField p_auteur;
    private javax.swing.JTextField pays;
    private javax.swing.JTable tb_Books;
    private javax.swing.JComboBox<String> theme;
    private javax.swing.JTextField titre;
    // End of variables declaration//GEN-END:variables
    private void setIcon(){
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Pictures/Library.png")));
    }
}
