
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fares
 */
public class Library extends javax.swing.JFrame {
    /**
     * Creates new form Library
     */
    public Library() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        B1 = new javax.swing.JLabel();
        B2 = new javax.swing.JLabel();
        B3 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        memoireRB = new javax.swing.JRadioButton();
        livreRB = new javax.swing.JRadioButton();
        B4 = new javax.swing.JLabel();
        B5 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Gestion de la bibliothèque");
        setMinimumSize(new java.awt.Dimension(540, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Subscribers.png"))); // NOI18N
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B1MouseClicked(evt);
            }
        });
        getContentPane().add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 50, -1));

        B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Books.png"))); // NOI18N
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B2MouseClicked(evt);
            }
        });
        getContentPane().add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, 40));

        B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Pret.png"))); // NOI18N
        B3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B3MouseClicked(evt);
            }
        });
        getContentPane().add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 60));

        Text2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        Text2.setForeground(new java.awt.Color(255, 255, 255));
        Text2.setText("Vous voulez rechercher un :");
        getContentPane().add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        memoireRB.setBackground(new java.awt.Color(255, 255, 255));
        memoireRB.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        memoireRB.setForeground(new java.awt.Color(255, 255, 255));
        memoireRB.setText("Mémoire");
        memoireRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memoireRBActionPerformed(evt);
            }
        });
        jPanel1.add(memoireRB);

        livreRB.setBackground(new java.awt.Color(255, 255, 255));
        livreRB.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        livreRB.setForeground(new java.awt.Color(255, 255, 255));
        livreRB.setText("Livre");
        livreRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livreRBActionPerformed(evt);
            }
        });
        jPanel1.add(livreRB);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 160, 30));

        B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Next.png"))); // NOI18N
        B4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B4MouseClicked(evt);
            }
        });
        getContentPane().add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 50, 40));

        B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Memoire.png"))); // NOI18N
        B5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B5MouseClicked(evt);
            }
        });
        getContentPane().add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, 50));

        Background.setBackground(new java.awt.Color(0, 0, 0));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/bg3.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void livreRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livreRBActionPerformed
        if(livreRB.isSelected())
            memoireRB.setSelected(false);
    }//GEN-LAST:event_livreRBActionPerformed

    private void memoireRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memoireRBActionPerformed
        if(memoireRB.isSelected())
            livreRB.setSelected(false);
    }//GEN-LAST:event_memoireRBActionPerformed

    private void B4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4MouseClicked
        if(livreRB.isSelected()||memoireRB.isSelected()){
            if(livreRB.isSelected()){
                new S_L_1().setVisible(true);
                this.setVisible(false);
                F_S_L.Call("livres");
            }
            if(memoireRB.isSelected()){
                new S_M_1().setVisible(true);
                this.setVisible(false);
                F_S_M.Call("memoires");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Les choix ne sont pas sélectionnés.");
        }
    }//GEN-LAST:event_B4MouseClicked

    private void B1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseClicked
        new Subscribers().setVisible(true);
    }//GEN-LAST:event_B1MouseClicked

    private void B2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseClicked
        new Books().setVisible(true);
    }//GEN-LAST:event_B2MouseClicked

    private void B5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5MouseClicked
        new Memory().setVisible(true);
    }//GEN-LAST:event_B5MouseClicked

    private void B3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MouseClicked
        new Pret().setVisible(true);
    }//GEN-LAST:event_B3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        DB_Managing connect = new DB_Managing();
        //connect.getData();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Library().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel B1;
    private javax.swing.JLabel B2;
    private javax.swing.JLabel B3;
    private javax.swing.JLabel B4;
    private javax.swing.JLabel B5;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Text2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton livreRB;
    private javax.swing.JRadioButton memoireRB;
    // End of variables declaration//GEN-END:variables
    
    private void setIcon(){
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Pictures/Library.png")));
    }
}
