
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fares
 */
public class Memory extends javax.swing.JFrame {

    /**
     * Creates new form Add_Memory
     */
    public Memory() {
        initComponents();
        Update_table();
        setDefaultCloseOperation(Memory.DISPOSE_ON_CLOSE);
        setIcon();
    }

        private void Update_table(){
    
    Connection con = null;
    Statement st = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    String query = "SELECT * FROM memoires";
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bibliotheque","root","");
            pst = con.prepareStatement(query);
            rs = pst.executeQuery();
            tb_Memory.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(SQLException ex){
            System.out.println("Error: "+ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Text1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        auteur = new javax.swing.JTextField();
        titre = new javax.swing.JTextField();
        n_encadr = new javax.swing.JTextField();
        a_univ = new javax.swing.JTextField();
        n_exmp = new javax.swing.JTextField();
        Insert_Memory = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Memory = new javax.swing.JTable();
        Update_Memory = new javax.swing.JLabel();
        Delete_Memory = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        id_M = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cdd = new javax.swing.JComboBox<>();
        theme = new javax.swing.JComboBox<>();
        Reset = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Gestion de la bibliothèque");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Text1.setForeground(new java.awt.Color(255, 255, 255));
        Text1.setText("Mémoire");
        getContentPane().add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Auteur:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Titre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nom d'encadreur");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Année universitaire:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Numéro d'exemplaire:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Théme:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CDD:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        auteur.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(auteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 80, -1));

        titre.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 80, -1));

        n_encadr.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(n_encadr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 80, -1));

        a_univ.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(a_univ, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 80, -1));

        n_exmp.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(n_exmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 80, -1));

        Insert_Memory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Add.png"))); // NOI18N
        Insert_Memory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Insert_MemoryMouseClicked(evt);
            }
        });
        getContentPane().add(Insert_Memory, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        tb_Memory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Memoire", "Auteur", "Titre", "Nom Encadreur", "année univ", "N° Exemplaire", "Theme", "CDD"
            }
        ));
        tb_Memory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_MemoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Memory);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 590, 350));

        Update_Memory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Update.png"))); // NOI18N
        Update_Memory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Update_MemoryMouseClicked(evt);
            }
        });
        getContentPane().add(Update_Memory, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        Delete_Memory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Delete.png"))); // NOI18N
        Delete_Memory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Delete_MemoryMouseClicked(evt);
            }
        });
        getContentPane().add(Delete_Memory, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID memoire :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        id_M.setBackground(new java.awt.Color(204, 204, 204));
        id_M.setEnabled(false);
        getContentPane().add(id_M, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 80, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("(AAAA/AAAA)");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 70, 20));

        cdd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "000", "100", "200", "300", "400", "500", "600", "700", "800", "900" }));
        getContentPane().add(cdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 80, -1));

        theme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Analytiques", "Algébrique", "Informatique", "Chimie", "Technologie", "Science" }));
        getContentPane().add(theme, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 80, -1));

        Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Delete_1.png"))); // NOI18N
        Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetMouseClicked(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        Background.setBackground(new java.awt.Color(204, 204, 204));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Background.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Insert_MemoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Insert_MemoryMouseClicked

        if( 
           auteur.getText().equals("") 
        || titre.getText().equals("") 
        || n_encadr.getText().equals("")
        || a_univ.getText().equals("")
        || n_exmp.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "Un ou plusieurs champs sont vides");
        }else{
            String input = a_univ.getText();
            if (input.matches("[A-Za-z]{1}")) {
                JOptionPane.showMessageDialog(null, "Vérifiez le format de l'année universitaire insérée");
            }else{
                try{ 
                    int N_exmp = Integer.parseInt(n_exmp.getText());

                    String Cdd = (String) cdd.getSelectedItem();
                    String Theme = (String) theme.getSelectedItem();
                    String d1 = a_univ.getText();      
                    char[] charArray1 = d1.toCharArray();

                    if(charArray1[4] == '/'){
                    try {
                        DB_Managing.InsertMemory(auteur.getText(), titre.getText(), n_encadr.getText(), a_univ.getText(), N_exmp, Theme, Cdd);
                        Update_table();
                        } catch (SQLException ex) {
                                //Logger.getLogger(Subscribers.class.getName()).log(Level.SEVERE, null, ex);
                                JOptionPane.showMessageDialog(null, "Vérifiez le format de l'année universitaire insérée");
                        }
                        }else{
                            JOptionPane.showMessageDialog(null, "Vérifiez le format de l'année universitaire insérée");
                        }
                    } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Vérifiez la valeur de numéro d'exemplaire insérée");
                }
            }
        }
    }//GEN-LAST:event_Insert_MemoryMouseClicked

    private void Update_MemoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_MemoryMouseClicked
        if( 
           auteur.getText().equals("") 
        || titre.getText().equals("") 
        || n_encadr.getText().equals("")
        || a_univ.getText().equals("")
        || n_exmp.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "Un ou plusieurs champs sont vides");
        }else{
            int idM = Integer.parseInt(id_M.getText());
            int N_exmp = Integer.parseInt(n_exmp.getText());
            String Cdd =  (String) cdd.getSelectedItem();
            String Theme =  (String) theme.getSelectedItem();
            
            String d1 = a_univ.getText();      
            char[] charArray1 = d1.toCharArray();
            
            if(charArray1[4] == '/'){
            try {
                DB_Managing.UpdateMemory(idM, auteur.getText(), titre.getText(), n_encadr.getText(), a_univ.getText(), N_exmp, Theme, Cdd);
                Update_table();
            } catch (SQLException ex) {
                    Logger.getLogger(Subscribers.class.getName()).log(Level.SEVERE, null, ex);
              }
            }else{
                JOptionPane.showMessageDialog(null, "Vérifiez le format de la date d'inscription insérée");
            }
        }
    }//GEN-LAST:event_Update_MemoryMouseClicked

    private void Delete_MemoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_MemoryMouseClicked

        if(id_M.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Le champ numéro ID memoire est vides");
        }else{
            int idM = Integer.parseInt(id_M.getText());
            DB_Managing.DeleteMemory(idM); 
            Update_table();
        }
    }//GEN-LAST:event_Delete_MemoryMouseClicked

    private void tb_MemoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_MemoryMouseClicked
        
        DefaultTableModel model = (DefaultTableModel) tb_Memory.getModel();
        int selectedRowIndex = tb_Memory.getSelectedRow();
        
        id_M.setText(model.getValueAt(selectedRowIndex, 0).toString());
        auteur.setText(model.getValueAt(selectedRowIndex, 1).toString());
        titre.setText(model.getValueAt(selectedRowIndex, 2).toString());
        n_encadr.setText(model.getValueAt(selectedRowIndex, 3).toString());
        a_univ.setText(model.getValueAt(selectedRowIndex, 4).toString());
        n_exmp.setText(model.getValueAt(selectedRowIndex, 5).toString());
        theme.setSelectedItem(model.getValueAt(selectedRowIndex, 6).toString());
        cdd.setSelectedItem(model.getValueAt(selectedRowIndex, 7).toString());
    }//GEN-LAST:event_tb_MemoryMouseClicked

    private void ResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseClicked
        id_M.setText(null);
        auteur.setText(null);
        titre.setText(null);
        n_encadr.setText(null);
        a_univ.setText(null);
        n_exmp.setText(null);
    }//GEN-LAST:event_ResetMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Delete_Memory;
    private javax.swing.JLabel Insert_Memory;
    private javax.swing.JLabel Reset;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Update_Memory;
    private javax.swing.JTextField a_univ;
    private javax.swing.JTextField auteur;
    private javax.swing.JComboBox<String> cdd;
    private javax.swing.JTextField id_M;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField n_encadr;
    private javax.swing.JTextField n_exmp;
    private javax.swing.JTable tb_Memory;
    private javax.swing.JComboBox<String> theme;
    private javax.swing.JTextField titre;
    // End of variables declaration//GEN-END:variables
    private void setIcon(){
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Pictures/Library.png")));
    }
}
