
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fares
 */
public class S_L_2 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public S_L_2() {
        initComponents();
        setIcon();
        //jPanel1.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Text1 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        IdRB = new javax.swing.JRadioButton();
        CddRB = new javax.swing.JRadioButton();
        Nb_exemplaireRB = new javax.swing.JRadioButton();
        B5 = new javax.swing.JLabel();
        B4 = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Gestion de la bibliothèque");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Text1.setForeground(new java.awt.Color(255, 255, 255));
        Text1.setText("GESTION DU BIBLIOTHEQUE ");
        getContentPane().add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, 30));

        Text3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        Text3.setForeground(new java.awt.Color(255, 255, 255));
        Text3.setText("Recherché par :");
        getContentPane().add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        IdRB.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        IdRB.setForeground(new java.awt.Color(255, 255, 255));
        IdRB.setText("ID");
        IdRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdRBActionPerformed(evt);
            }
        });

        CddRB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CddRB.setForeground(new java.awt.Color(255, 255, 255));
        CddRB.setText("CDD");
        CddRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CddRBActionPerformed(evt);
            }
        });

        Nb_exemplaireRB.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Nb_exemplaireRB.setForeground(new java.awt.Color(255, 255, 255));
        Nb_exemplaireRB.setText("Nb exemplaire");
        Nb_exemplaireRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nb_exemplaireRBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(IdRB)
                .addGap(28, 28, 28)
                .addComponent(CddRB)
                .addGap(18, 18, 18)
                .addComponent(Nb_exemplaireRB)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IdRB, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Nb_exemplaireRB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(CddRB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, 30));

        B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Back.png"))); // NOI18N
        B5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B5MouseClicked(evt);
            }
        });
        getContentPane().add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 50, 40));

        B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Next.png"))); // NOI18N
        B4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B4MouseClicked(evt);
            }
        });
        getContentPane().add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 50, 40));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Home.png"))); // NOI18N
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/bg3.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdRBActionPerformed
        if(IdRB.isSelected())
        CddRB.setSelected(false);
        Nb_exemplaireRB.setSelected(false);
    }//GEN-LAST:event_IdRBActionPerformed

    private void CddRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CddRBActionPerformed
        if(CddRB.isSelected())
        IdRB.setSelected(false);
        Nb_exemplaireRB.setSelected(false);
    }//GEN-LAST:event_CddRBActionPerformed

    private void Nb_exemplaireRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nb_exemplaireRBActionPerformed
        if(Nb_exemplaireRB.isSelected())
        CddRB.setSelected(false);
        IdRB.setSelected(false);
    }//GEN-LAST:event_Nb_exemplaireRBActionPerformed

    private void B5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5MouseClicked
        new S_L_1().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_B5MouseClicked

    private void B4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4MouseClicked
        
        int i = 0;
        if(CddRB.isSelected()){
        new F_S_L().setVisible(true);
        this.setVisible(false);
            i++;
            F_S_L.Call("CDD");
        }
        if(IdRB.isSelected()){
        new F_S_L().setVisible(true);
        this.setVisible(false);
            i++;
            F_S_L.Call("identifient");
        }
        if(Nb_exemplaireRB.isSelected()){
        new F_S_L().setVisible(true);
        this.setVisible(false);
            i++;
            F_S_L.Call("nb_exemplaire");
        }
        if(i == 0){
            JOptionPane.showMessageDialog(null, "Les choix ne sont pas sélectionnés.");
        }        
    }//GEN-LAST:event_B4MouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        new Library().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel B4;
    private javax.swing.JLabel B5;
    private javax.swing.JLabel Background;
    private javax.swing.JRadioButton CddRB;
    private javax.swing.JLabel Home;
    private javax.swing.JRadioButton IdRB;
    private javax.swing.JRadioButton Nb_exemplaireRB;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private void setIcon(){
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Pictures/Library.png")));
    }
}
