
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fares
 */
public class Subscribers extends javax.swing.JFrame {
        
    /**
     * Creates new form N_Books
     */
    public Subscribers() {
                
        initComponents();        
        setDefaultCloseOperation(Subscribers.DISPOSE_ON_CLOSE);
        Display_table();
        setIcon();
    }
    
    private void Display_table(){
    
    Connection con = null;
    Statement st = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    String query = "SELECT * FROM emprenteur";
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bibliotheque","root","");
            pst = con.prepareStatement(query);
            rs = pst.executeQuery();
            tb_Subs.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(SQLException ex){
            System.out.println("Error: "+ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Text1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        categorie = new javax.swing.JComboBox<>();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        adresse = new javax.swing.JTextField();
        institut = new javax.swing.JTextField();
        nv_etudes = new javax.swing.JComboBox<>();
        Insert_Subs = new javax.swing.JLabel();
        Update_Subs = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        n_Ordre = new javax.swing.JTextField();
        Delete_Subs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Subs = new javax.swing.JTable();
        Reset = new javax.swing.JLabel();
        d_insc = new com.toedter.calendar.JDateChooser();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Gestion de la bibliothèque");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Text1.setForeground(new java.awt.Color(255, 255, 255));
        Text1.setText("Emprunteur ");
        getContentPane().add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nom:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Prenom");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Adresse:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Catégorie:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date d'inscription:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Institut:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Niveau d'études:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        categorie.setBackground(new java.awt.Color(204, 204, 204));
        categorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Etudiant", "Professeur", "Autre" }));
        categorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorieActionPerformed(evt);
            }
        });
        getContentPane().add(categorie, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 140, -1));

        nom.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 140, -1));

        prenom.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 140, -1));

        adresse.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(adresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 140, -1));

        institut.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(institut, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 140, -1));

        nv_etudes.setBackground(new java.awt.Color(204, 204, 204));
        nv_etudes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L1", "L2", "L3", "M1", "M2", "Doctorat", "none" }));
        getContentPane().add(nv_etudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 140, -1));

        Insert_Subs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Add.png"))); // NOI18N
        Insert_Subs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Insert_Subs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Insert_SubsMouseClicked(evt);
            }
        });
        getContentPane().add(Insert_Subs, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        Update_Subs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Update.png"))); // NOI18N
        Update_Subs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Update_SubsMouseClicked(evt);
            }
        });
        getContentPane().add(Update_Subs, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Numéro d'ordre:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        n_Ordre.setBackground(new java.awt.Color(204, 204, 204));
        n_Ordre.setEnabled(false);
        getContentPane().add(n_Ordre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 140, -1));

        Delete_Subs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Delete.png"))); // NOI18N
        Delete_Subs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Delete_SubsMouseClicked(evt);
            }
        });
        getContentPane().add(Delete_Subs, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 328, 40, 50));

        tb_Subs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N_Ordre", "Nom", "Prénom", "Adresse", "Categorie", "D_Inscription", "Institutl", "Nv_Etudes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_Subs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_SubsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Subs);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 600, 320));

        Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Delete_1.png"))); // NOI18N
        Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetMouseClicked(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        d_insc.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(d_insc, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 230, 140, -1));

        Background.setBackground(new java.awt.Color(204, 204, 204));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Background.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Insert_SubsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Insert_SubsMouseClicked
         
        if(    nom.getText().equals("") 
            || prenom.getText().equals("") 
            || adresse.getText().equals("")
            || d_insc.getDate() == null
            || institut.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "Un ou plusieurs champs sont vides");
        }else{
                Date date = d_insc.getDate(); 
                java.sql.Date sgldate = new java.sql.Date(date.getTime());
            
            try {
                String Categorie = (String) categorie.getSelectedItem();
                String Nv_etudes = (String) nv_etudes.getSelectedItem();
        
                DB_Managing.InsertSubsc(nom.getText(), prenom.getText(), adresse.getText(), Categorie, sgldate, institut.getText(), Nv_etudes);
                Display_table();
                } catch (SQLException ex) {
                    Logger.getLogger(Subscribers.class.getName()).log(Level.SEVERE, null, ex);
                  }
        }
    }//GEN-LAST:event_Insert_SubsMouseClicked

    private void Update_SubsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_SubsMouseClicked
    
        if(    n_Ordre.getText().equals("") 
            || nom.getText().equals("") 
            || prenom.getText().equals("") 
            || adresse.getText().equals("")
            || d_insc.getDate().equals("")
            || institut.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "Un ou plusieurs champs sont vides");
        }else{
            Date date = d_insc.getDate();    
            java.sql.Date sgldate = new java.sql.Date(date.getTime());
            
            try {
                String Categorie = (String) categorie.getSelectedItem();
                String Nv_etudes = (String) nv_etudes.getSelectedItem();
                int n_ordr = Integer.parseInt(n_Ordre.getText());
                DB_Managing.UpdateSubsc(n_ordr, nom.getText(), prenom.getText(), adresse.getText(), Categorie, sgldate, institut.getText(), Nv_etudes);
                Display_table();
                } catch (SQLException ex) {
                    Logger.getLogger(Subscribers.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Update_SubsMouseClicked

    private void Delete_SubsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_SubsMouseClicked
         
        if(n_Ordre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Le champ numéro d'ordre est vides");
        }else{
            int n_ordr = Integer.parseInt(n_Ordre.getText());
            DB_Managing.DeleteSubsc(n_ordr); 
            Display_table();
        }
    }//GEN-LAST:event_Delete_SubsMouseClicked

    private void tb_SubsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_SubsMouseClicked

        try {
            DefaultTableModel model = (DefaultTableModel) tb_Subs.getModel();
            int selectedRowIndex = tb_Subs.getSelectedRow();
            
            n_Ordre.setText(model.getValueAt(selectedRowIndex, 0).toString());
            nom.setText(model.getValueAt(selectedRowIndex, 1).toString());
            prenom.setText(model.getValueAt(selectedRowIndex, 2).toString());
            adresse.setText(model.getValueAt(selectedRowIndex, 3).toString());
            categorie.setSelectedItem(model.getValueAt(selectedRowIndex, 4).toString());
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(selectedRowIndex, 5).toString());
            d_insc.setDate(date);
            institut.setText(model.getValueAt(selectedRowIndex, 6).toString());
            nv_etudes.setSelectedItem(model.getValueAt(selectedRowIndex, 7).toString());
        } catch (ParseException ex) {
            Logger.getLogger(Subscribers.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_tb_SubsMouseClicked

    private void categorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorieActionPerformed
        nv_etudes.setEnabled(true);
        if((String) categorie.getSelectedItem() == "Professeur"){
            nv_etudes.setEnabled(false);
            nv_etudes.setSelectedItem("none");
        }
    }//GEN-LAST:event_categorieActionPerformed

    private void ResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseClicked
        n_Ordre.setText(null);
        nom.setText(null);
        prenom.setText(null);
        adresse.setText(null);
        d_insc.setDate(null);
        institut.setText(null);
    }//GEN-LAST:event_ResetMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Delete_Subs;
    private javax.swing.JLabel Insert_Subs;
    private javax.swing.JLabel Reset;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Update_Subs;
    private javax.swing.JTextField adresse;
    private javax.swing.JComboBox<String> categorie;
    private com.toedter.calendar.JDateChooser d_insc;
    private javax.swing.JTextField institut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField n_Ordre;
    private javax.swing.JTextField nom;
    private javax.swing.JComboBox<String> nv_etudes;
    private javax.swing.JTextField prenom;
    private javax.swing.JTable tb_Subs;
    // End of variables declaration//GEN-END:variables
    private void setIcon(){
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Pictures/Library.png")));
    }
}